machine:
  php:
    version: 7.0.11
dependencies:
  post:
    - sudo rm /etc/apache2/mods-enabled/php5.load
    - sudo cp .circle-server-config /etc/apache2/sites-available
    - sudo service apache2 restart