services:
  - mysql
before_install:
  - mysql -u root < server/database/SQL/projetx.sql
before_script: composer require atoum/atoum
script: vendor/bin/atoum
language: php
php:
    - '7.0'
script:
    - php server/tests/atoum.phar