dist: trusty
sudo: required
addons:
  sonarcloud:
    organization: "your_organization_key"
    token:
      secure: "your_token_encrypted_with_travis_encrypt_tool"
services:
  - mysql
language: php
php:
  - '7.0'
jdk:
  - oraclejdk8
before_install:
  - sudo apt-get update
  
  # database
  - mysql -u root < backend/database/database/projetx.sql
  
  # apache server 
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  
  
  # configure apache virtual hosts
  - sudo cp -f .travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart
  
before_script: 
    - cd backend/
    - mkdir -p build/logs
    - composer update
script:
    - php phpunit.phar
    - sonar-scanner
after_script:
    - php vendor/bin/coveralls -v
cache:
  directories:
    - '$HOME/.sonar/cache'