services:
  - mysql
language: php
env:
  CODECLIMATE_REPO_TOKEN: f5f012a16b4dabfeff9f2e1484baac76ac38b80e3f1c053fbf5517d1da8d246e
php:
    - '7.0'
before_install:
  - sudo apt-get update
  
  # database
  - mysql -u root < server/database/SQL/projetx.sql
  
  # apache server 
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  
  # enable php-fpm
  #- sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  #- sudo a2enmod rewrite actions fastcgi alias
  #- echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  #- ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  
  # configure apache virtual hosts
  - sudo cp -f .travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart
  
before_script: 
    - cd server/
    - composer update
script:
    - php tests/atoum.phar -c tests/.atoum.php
repo_token: qIapEkNDgw3Gjr4Z23S59PHXjUHONoZVy